require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomerCupcakesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomerCupcake. As you add validations to CustomerCupcake, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => "Aliya", :size => "small", :flavor => "Vanilla", :icing => "Vanilla", :additional_topping => "Chocolate", :customer_id => 1}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomerCupcakesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all customer_cupcakes as @customer_cupcakes" do
      customer_cupcake = CustomerCupcake.create! valid_attributes
      get :index, {}, valid_session
      assigns(:customer_cupcakes).should eq([customer_cupcake])
    end
  end

  describe "GET show" do
    it "assigns the requested customer_cupcake as @customer_cupcake" do
      customer_cupcake = CustomerCupcake.create! valid_attributes
      get :show, {:id => customer_cupcake.to_param}, valid_session
      assigns(:customer_cupcake).should eq(customer_cupcake)
    end
  end

  describe "GET new" do
    it "assigns a new customer_cupcake as @customer_cupcake" do
      get :new, {}, valid_session
      assigns(:customer_cupcake).should be_a_new(CustomerCupcake)
    end
  end

  describe "GET edit" do
    it "assigns the requested customer_cupcake as @customer_cupcake" do
      customer_cupcake = CustomerCupcake.create! valid_attributes
      get :edit, {:id => customer_cupcake.to_param}, valid_session
      assigns(:customer_cupcake).should eq(customer_cupcake)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomerCupcake" do
        expect {
          post :create, {:customer_cupcake => valid_attributes}, valid_session
        }.to change(CustomerCupcake, :count).by(1)
      end

      it "assigns a newly created customer_cupcake as @customer_cupcake" do
        post :create, {:customer_cupcake => valid_attributes}, valid_session
        assigns(:customer_cupcake).should be_a(CustomerCupcake)
        assigns(:customer_cupcake).should be_persisted
      end

      it "redirects to the created customer_cupcake" do
        post :create, {:customer_cupcake => valid_attributes}, valid_session
        response.should redirect_to(CustomerCupcake.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customer_cupcake as @customer_cupcake" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCupcake.any_instance.stub(:save).and_return(false)
        post :create, {:customer_cupcake => { "name" => "invalid value" }}, valid_session
        assigns(:customer_cupcake).should be_a_new(CustomerCupcake)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCupcake.any_instance.stub(:save).and_return(false)
        post :create, {:customer_cupcake => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customer_cupcake" do
        customer_cupcake = CustomerCupcake.create! valid_attributes
        # Assuming there are no other customer_cupcakes in the database, this
        # specifies that the CustomerCupcake created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomerCupcake.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => customer_cupcake.to_param, :customer_cupcake => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested customer_cupcake as @customer_cupcake" do
        customer_cupcake = CustomerCupcake.create! valid_attributes
        put :update, {:id => customer_cupcake.to_param, :customer_cupcake => valid_attributes}, valid_session
        assigns(:customer_cupcake).should eq(customer_cupcake)
      end

      it "redirects to the customer_cupcake" do
        customer_cupcake = CustomerCupcake.create! valid_attributes
        put :update, {:id => customer_cupcake.to_param, :customer_cupcake => valid_attributes}, valid_session
        response.should redirect_to(customer_cupcake)
      end
    end

    describe "with invalid params" do
      it "assigns the customer_cupcake as @customer_cupcake" do
        customer_cupcake = CustomerCupcake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCupcake.any_instance.stub(:save).and_return(false)
        put :update, {:id => customer_cupcake.to_param, :customer_cupcake => { "name" => "invalid value" }}, valid_session
        assigns(:customer_cupcake).should eq(customer_cupcake)
      end

      it "re-renders the 'edit' template" do
        customer_cupcake = CustomerCupcake.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCupcake.any_instance.stub(:save).and_return(false)
        put :update, {:id => customer_cupcake.to_param, :customer_cupcake => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customer_cupcake" do
      customer_cupcake = CustomerCupcake.create! valid_attributes
      expect {
        delete :destroy, {:id => customer_cupcake.to_param}, valid_session
      }.to change(CustomerCupcake, :count).by(-1)
    end

    it "redirects to the customer_cupcakes list" do
      customer_cupcake = CustomerCupcake.create! valid_attributes
      delete :destroy, {:id => customer_cupcake.to_param}, valid_session
      response.should redirect_to(customer_cupcakes_url)
    end
  end

end
